name: Create Release

on:
  create:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'SNAPSHOT')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        token: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            This is a new release!
          draft: false
          prerelease: false