name: Create Release

on:
  create:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'SNAPSHOT')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref.replace('refs/tags/', '') }}
          body: |
            This is release ${{ github.ref.replace('refs/tags/', '') }}
          draft: false
          prerelease: false
