name: Create Release

on:
  create:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'SNAPSHOT')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This is a new release!
          draft: false
          prerelease: false